[package]
name = "NoSchoolTomorrowRust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
openmeteo-rs = "1.0.0"
reqwest = "0.13.4"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
linfa = "0.8.1"
linfa-trees = "0.8.1"
ndarray = "0.16"
csv = "1.4.0"
serde = { version = "1.0.229", features = ["derive"] }
pancurses = { version = "0.17.0", features = ["win32"] }